// Generated by ts-to-zod
import { z } from 'zod'
import { Json } from './database.types'

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
)

export const predictionsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  is_anonymous: z.boolean().nullable(),
  prediction: z.string(),
  question_id: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
})

export const predictionsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_anonymous: z.boolean().optional().nullable(),
  prediction: z.string(),
  question_id: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
})

export const predictionsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_anonymous: z.boolean().optional().nullable(),
  prediction: z.string().optional(),
  question_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
})

export const predictionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('fk_question'),
    columns: z.tuple([z.literal('question_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('questions'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
  z.object({
    foreignKeyName: z.literal('fk_user'),
    columns: z.tuple([z.literal('user_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('profiles'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const profilesRowSchema = z.object({
  id: z.string(),
  updated_at: z.string().nullable(),
  username: z.string().nullable(),
})

export const profilesInsertSchema = z.object({
  id: z.string(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
})

export const profilesUpdateSchema = z.object({
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  username: z.string().optional().nullable(),
})

export const profilesRelationshipsSchema = z.tuple([])

export const visibilityTypeSchema = z.union([
  z.literal('public'),
  z.literal('private'),
  z.literal('friends'),
])

export const questionsInsertSchema = z.object({
  allow_anonymous_predictions: z.boolean().optional().nullable(),
  author_id: z.string(),
  created_at: z.string().optional().nullable(),
  deadline: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  last_activity_at: z.string().optional().nullable(),
  last_updated_at: z.string().optional().nullable(),
  show_prediction_count: z.boolean().optional().nullable(),
  title: z.string(),
  total_predictions: z.number().optional().nullable(),
  view_count: z.number().optional().nullable(),
  visibility: visibilityTypeSchema,
})

export const questionsUpdateSchema = z.object({
  allow_anonymous_predictions: z.boolean().optional().nullable(),
  author_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  deadline: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  last_activity_at: z.string().optional().nullable(),
  last_updated_at: z.string().optional().nullable(),
  show_prediction_count: z.boolean().optional().nullable(),
  title: z.string().optional(),
  total_predictions: z.number().optional().nullable(),
  view_count: z.number().optional().nullable(),
  visibility: visibilityTypeSchema.optional(),
})

export const questionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal('fk_author'),
    columns: z.tuple([z.literal('author_id')]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal('profiles'),
    referencedColumns: z.tuple([z.literal('id')]),
  }),
])

export const questionsRowSchema = z.object({
  allow_anonymous_predictions: z.boolean().nullable(),
  author_id: z.string(),
  created_at: z.string().nullable(),
  deadline: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  last_activity_at: z.string().nullable(),
  last_updated_at: z.string().nullable(),
  show_prediction_count: z.boolean().nullable(),
  title: z.string(),
  total_predictions: z.number().nullable(),
  view_count: z.number().nullable(),
  visibility: visibilityTypeSchema,
})
