/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod'
import * as generated from './schema.zod'
export type PublicVisibilityType = z.infer<
  typeof generated.publicVisibilityTypeSchema
>
export type Json = z.infer<typeof generated.jsonSchema>
export type PublicPredictionsRowSchema = z.infer<
  typeof generated.publicPredictionsRowSchemaSchema
>
export type PublicPredictionsInsertSchema = z.infer<
  typeof generated.publicPredictionsInsertSchemaSchema
>
export type PublicPredictionsUpdateSchema = z.infer<
  typeof generated.publicPredictionsUpdateSchemaSchema
>
export type PublicPredictionsRelationshipsSchema = z.infer<
  typeof generated.publicPredictionsRelationshipsSchemaSchema
>
export type PublicProfilesRowSchema = z.infer<
  typeof generated.publicProfilesRowSchemaSchema
>
export type PublicProfilesInsertSchema = z.infer<
  typeof generated.publicProfilesInsertSchemaSchema
>
export type PublicProfilesUpdateSchema = z.infer<
  typeof generated.publicProfilesUpdateSchemaSchema
>
export type PublicProfilesRelationshipsSchema = z.infer<
  typeof generated.publicProfilesRelationshipsSchemaSchema
>
export type PublicQuestionsRowSchema = z.infer<
  typeof generated.publicQuestionsRowSchemaSchema
>
export type PublicQuestionsInsertSchema = z.infer<
  typeof generated.publicQuestionsInsertSchemaSchema
>
export type PublicQuestionsUpdateSchema = z.infer<
  typeof generated.publicQuestionsUpdateSchemaSchema
>
export type PublicQuestionsRelationshipsSchema = z.infer<
  typeof generated.publicQuestionsRelationshipsSchemaSchema
>
export type PublicGetPredictionsCountArgsSchema = z.infer<
  typeof generated.publicGetPredictionsCountArgsSchemaSchema
>
export type PublicGetPredictionsCountReturnsSchema = z.infer<
  typeof generated.publicGetPredictionsCountReturnsSchemaSchema
>
